# Generated by Django 4.2 on 2024-09-05 18:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='../placeholder_profile_xnpcwj.webp', max_length=255, verbose_name='image'),
        ),
    ]
