# Generated by Django 3.2.4 on 2024-09-12 07:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default_profile_qdjgyp', max_length=255, verbose_name='image'),
        ),
    ]
